version: '3'
services:
    backend:
        container_name: backend_container
        restart: always
        image: ghcr.io/fga-eps-mds/2020.1-gaiadex-backend:homolog
        ports:
            - 3000:3000
        volumes: 
            - ./src:/app/src
        links: 
            - mongo
    mongo:
        container_name: mongo_container
        build: 
            dockerfile: homologDataBaseDockerfile
            context: .
        ports: 
            - 27017:27017