version: '3.9'

volumes:
  lakoste_data:
    name: lakoste_data

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - lakoste_data:/var/lib/postgresql/data

  app:
    container_name: lakoste
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
