version: "2"

services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    volumes:
      - "elasticsearch_data:/bitnami/elasticsearch"
  kibana:
    image: docker.io/bitnami/kibana:8
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local

  kibana_data:
    driver: local
