services:
  robot-base:
    container_name: robot-dev
    network_mode: "host"
    build:
      context: .
      ssh: 
        - default
    volumes:
      - "./src:/workspaces/ros2_ws/src"
    environment:
      - MAIN_WS=/workspaces/ros2_ws
  windows-wsl-nvidia:
    extends: robot-base
    build:
      target: robot_dev_wsl_nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
      - "/usr/lib/wsl:/usr/lib/wsl"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  windows-wsl:
    extends: robot-base
    build:
      target: robot_dev_wsl
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
      - "/usr/lib/wsl:/usr/lib/wsl"
  mac:
    extends: robot-base
    build:
      target: robot_dev_mac
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  linux:
    extends: robot-base
    build:
      target: robot_dev_linux
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - type: bind
        source: ./.docker.xauth
        target: /tmp/.docker.xauth

