services:
  alive-server:
    image: ghcr.io/wejick/alive-server:latest
    ports:
    - 8081:8081
    volumes:
    - sqlite-db:/app/db/
networks:
  default:
    name: workspace_default
volumes:
  sqlite-db: