version: "3.5"

services:
  nginx:
    image: {{ ix_lib.charts.nginx.images.nginx_image_name("latest") }}
    container_name: {{ ix_lib.base.containers.container_name("nginx") }}
    ports:
      - {{ ix_lib.charts.nginx.images.port_to_bind("21119") }}
    networks:
      - NGINX


networks:
  NGINX:
    name: {{ network }}

