version: '3'

services:
  minio:
    image: minio/minio
    command: minio server /data
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    restart: always
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/archived;
      /usr/bin/mc anonymous set public myminio/archived;
      /usr/bin/mc mb myminio/archived-backup;
      /usr/bin/mc anonymous set public myminio/archived-backup;
      exit 0;
      "
volumes:
  data: