#   
#         _ _            ____             _           __  ___                                       __ 
#        (_|_)______ _  / __/__ _____  __(_)______   /  |/  /__ ____  ___ ____ ____ __ _  ___ ___  / /_
#       / / / __/ _ `/ _\ \/ -_) __/ |/ / / __/ -_) / /|_/ / _ `/ _ \/ _ `/ _ `/ -_)  ' \/ -_) _ \/ __/
#    __/ /_/_/  \_,_/ /___/\__/_/  |___/_/\__/\__/ /_/  /_/\_,_/_//_/\_,_/\_, /\__/_/_/_/\__/_//_/\__/ 
#   |___/                                                                /___/                         
#   
#   Docker Compose for Run Jira Service Manegment (Servicer Desk)
#   Test for Jira ServiceManegment 8.x ~ 9.x
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=150.50.50.0/24 my-net

version: "3.4"
services:
  servicemanagement:
    image: atlassian/jira-servicemanagement:latest  
    restart: always
    container_name: servicemanagement
    hostname: servicemanagement
    environment:      
      ATL_DB_DRIVER: 'org.postgresql.Driver'
      ATL_DB_TYPE: 'postgres72'
      ATL_JDBC_URL: 'jdbc:postgresql://db-jira:5432/jira'
      ATL_JDBC_USER: 'jira'
      ATL_JDBC_PASSWORD: 'Ljp%j5x>ELVdt8V47L2'
      #   If Use Reverse Proxy Uncomment this Line
      #ATL_TOMCAT_SCHEME: 'https'
      #ATL_TOMCAT_SECURE: 'true'
      #ATL_PROXY_PORT: '443'
      #ATL_PROXY_NAME: 'jira.my-site.com'
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m
    volumes:
      - servicemanagement-vol:/var/atlassian/application-data/jira
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    networks:
      my-net:
    depends_on:
      - postgressql-jira
    ports:
      - 8080:8080

  postgressql-servicemanagement:
    image: postgres
    restart: always
    container_name: postgressql-servicemanagement
    hostname: postgressql-servicemanagement
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: '0Ljp%j5x>ELVdt8V47L2'
    volumes:
      - postgresql-data-servicemanagement:/var/lib/postgresql/data
    networks:
      my-net:
       aliases:
        - db-jiras

networks:
  my-net:
    external: true
volumes:
  postgresql-data-servicemanagement:
    name: postgresql-data-servicemanagement
  servicemanagement-vol:
    name: servicemanagement-vol

