version: "3.8"
services:
  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user@1234
      POSTGRES_DB: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: user@1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata: 
  pgadmin-data: 