version: '3.3'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 6831:6831/udp
      - 16686:16686

  redpanda:
    image: vectorized/redpanda
    ports:
      - 9092:9092
    command:
      - 'redpanda start'
      - '--smp 1'
      - '--overprovisioned'
      - '--kafka-addr 0.0.0.0:9092'
      - '--advertise-kafka-addr localhost:9092'
