version: '3.8'
services:
  user-server:
    container_name:  user-server
    restart: on-failure:3
    image: dev/dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    build:
        context: ../
        dockerfile: docker/dev/dockerfile
    volumes:
      - ../server/src:/server/src 
    networks:
      - user-network
networks:
  user-network:
    driver: bridge
