---
version: "3"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: r0
      CLICKHOUSE_USER: demouser
      CLICKHOUSE_PASSWORD: 239QV8JkGmF9AZM
    hostname: clickhouse-0.localhost
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./docker/clickhouse/init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro

  vector:
    image: timberio/vector:0.23.0-debian
    container_name: vector
    ports:
      - 8888:8888
    volumes: 
      - $PWD/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - clickhouse

  grafana:
    build: .
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: 'ClickHouse'
            type: 'grafana-clickhouse-datasource'
            isDefault: true
            jsonData:
              defaultDatabase: r0
              port: 9000
              server: clickhouse-0.localhost
              username: demouser
              tlsSkipVerify: false
            secureJsonData:
              password: 239QV8JkGmF9AZM
            editable: true
        EOF
        mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboard.yaml
        apiVersion: 1
        providers:
          - name: demo-logs
            type: file
            updateIntervalSeconds: 30
            options:
              path:  /var/lib/grafana/dashboards
              foldersFromFilesStructure: true
        EOF
        /run.sh
    ports:
      - "3000:3000"
