version: "3.7"

volumes:

  volume-mysql:
    driver: local

  volume-sscms:
    driver: local

services:

  sscms-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: mysql-db
    volumes:
      - volume-mysql:/var/lib/mysql

  sscms-core:
    depends_on:
      - sscms-mysql
    image: "sscms/core"
    restart: always
    ports:
      - "80:80"
    environment:
      SSCMS_SECURITY_KEY: e2a3d303-ac9b-41ff-9154-930710af0845
      SSCMS_DATABASE_TYPE: MySQL
      SSCMS_DATABASE_HOST: sscms-mysql
      SSCMS_DATABASE_USER: root
      SSCMS_DATABASE_PASSWORD: mysql-password
      SSCMS_DATABASE_NAME: mysql-db
    volumes:
      - volume-sscms:/app/wwwroot

# docker-compose up -d
# docker-compose down

# Browse to: http://localhost/ss-admin/
