# For local development only.

version: '3'

services:
  cphalcon-8.0:
    container_name: cphalcon-8.0
    hostname: cphalcon-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

  cphalcon-8.1:
    container_name: cphalcon-8.1
    hostname: cphalcon-81
    build: docker/8.1
    working_dir: /srv
    ports:
      - "9501:9501"
    volumes:
      - .:/srv

  cphalcon-8.2:
    container_name: cphalcon-8.2
    hostname: cphalcon-82
    build: docker/8.2
    working_dir: /srv
    volumes:
      - .:/srv

  cphalcon-8.3:
    container_name: cphalcon-8.3
    hostname: cphalcon-83
    build: docker/8.3
    working_dir: /srv
    volumes:
      - .:/srv

  mysql:
    container_name: cphalcon-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret

  postgres:
    container_name: cphalcon-postgres
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon

  redis:
    container_name: cphalcon-redis
    image: redis:5-alpine
    ports:
      - "6379:6379"

  memcached:
    container_name: cphalcon-memcached
    image: memcached:1.5-alpine
