version: "3"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "matomo_db_data:/bitnami/mariadb"
  matomo:
    image: docker.io/bitnami/matomo:4
    ports:
      - "8080:8080"
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - MATOMO_USERNAME=user
      - MATOMO_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "matomo_data:/bitnami/matomo"
    depends_on:
      - mariadb
volumes:
  matomo_db_data:
    driver: local
  matomo_data:
    driver: local
