version: '2'

services:
  ms:
    image: easypi/metasploit-arm
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf
    links:
      - db
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4
      - /etc/localtime:/etc/localtime:ro
  db:
    image: easypi/postgres-arm
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
