frontend:
  image: java:8-jre
  links:
    - person
  ports:
   - "8081:8081"
  volumes:
   - docker/volume-frontend:/frontend
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/frontend/FrontendApplication.jar", "server", "/frontend/config.yml"]

authentication:
  image: java:8-jre
  ports:
   - "8082:8082"
  volumes:
   - docker/volume-authentication:/authentication
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/authentication/AuthenticationApplication.jar", "server", "/authentication/config.yml"]

authorisation:
  image: java:8-jre
  ports:
   - "8083:8083"
  volumes:
   - docker/volume-authorisation:/authorisation
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/authorisation/AuthorisationApplication.jar", "server", "/authorisation/config.yml"]

session:
  image: java:8-jre
  ports:
   - "8084:8084"
  volumes:
   - docker/volume-session:/session
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/session/SessionApplication.jar", "server", "/session/config.yml"]

person:
  image: java:8-jre
  links:
     - authorisation
  ports:
   - "8085:8085"
  volumes:
   - docker/volume-person:/person
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/person/PersonApplication.jar", "server", "/person/config.yml"]

web:
  build: docker/image-nginx-lua/.
  links:
   - frontend
   - authentication
   - session
   - person
  ports:
   - "8080:8080"
  volumes:
   - docker/volume-nginx-conf.d:/opt/nginx/conf
   - docker/volume-log:/var/log/nginx
