version: '3.9'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns@sha256:9f55e3ad0e88bee4b74c178c82fa622db14ed24b9e723d80701bccb00231a9ee
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
