version: "3.2"

services:
 db:
  image: mysql:5.7
  restart: always
  volumes:
   - type: bind
     source: "db_data" 
     target: "/var/lib/mysql"
  environment:
   MYSQL_ROOT_PASSWORD: db
   MYSQL_DATABASE: wordpress
 wordpress:
  image: wordpress:latest
  restart: always
  volumes:
   - type: bind 
     source: "wp_data"
     target: "/var/www/html"
  ports:
   - "8080:80"
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_NAME: wordpress
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: db
  depends_on:
   - db
volumes:
 db_data:
 wp_data:
