services:
  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=America/Vancouver

      - LOG_TYPE=BOTH
      - LOG_LEVEL=INFO

      - TRAEFIK_VERSION=2
      - CF_EMAIL=email@example.com
      - CF_TOKEN=fbSx3dk3A3mJ6UukLQ7zRbo63H5UdsGSCqQnTvbJDgyQaTp
      - RC_TYPE=CNAME

      - TARGET_DOMAIN=host.example.org
      - DOMAIN1=example.org
      - DOMAIN1_ZONE_ID=1234567890
      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1

      #- TRAEFIK_FILTER_LABEL=traefik.constraint
      #- TRAEFIK_FILTER=proxy-public
    networks:
      - services
    restart: always

networks:
  services:
    external: true
