version: "3"

services:
        
  ecs-node:
    image: ecredits/node:1.13.5-ecs-2
    volumes:
      - ./datadir/:/root/.ethereum
   
    restart: always
    hostname: ecs-node
    ports:
      - 8545:8545   # rpc
      - 30303:30303/tcp # p2p
      - 30303:30303/udp
      - 6060:6060   # metrics
    environment:
      - POD_NAME
    entrypoint:
      - sh
      - -c
      - >
        set -xe;

        geth
        --ecs
        --syncmode full
        --gcmode archive
        --http
        --http.api txpool,eth,net,debug,web3
        --http.addr "0.0.0.0"
        --http.vhosts "*"
        --http.corsdomain "*"
        --txpool.pricelimit 1
        --rpc.txfeecap 0
        --verbosity 3
        --metrics
        --metrics.addr 0.0.0.0
        --metrics.expensive
