version: "3.9"

x-base-service: &base
  image: node:18-slim
  entrypoint: sh
  working_dir: /app
  volumes:
    - .:/app
    - /app/node_modules

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: duelyst
      POSTGRES_PASSWORD: duelyst
      POSTGRES_DB: duelyst
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    profiles:
      - donotstart
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
    depends_on:
      - db

  api:
    <<: *base
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
      FIREBASE_URL: ${FIREBASE_URL}
      FIREBASE_LEGACY_TOKEN: ${FIREBASE_LEGACY_TOKEN}
    command: docker/start.sh api
    depends_on:
      - db
      - redis

  game:
    <<: *base
    ports:
      - 8001:8001
    environment:
      REDIS_HOST: redis
      FIREBASE_URL: ${FIREBASE_URL}
      FIREBASE_LEGACY_TOKEN: ${FIREBASE_LEGACY_TOKEN}
    command: docker/start.sh game
    depends_on:
      - redis

  sp:
    <<: *base
    ports:
      - 8000:8000
    environment:
      REDIS_HOST: redis
      FIREBASE_URL: ${FIREBASE_URL}
      FIREBASE_LEGACY_TOKEN: ${FIREBASE_LEGACY_TOKEN}
    command: docker/start.sh sp
    depends_on:
      - redis

  worker:
    <<: *base
    environment:
      REDIS_HOST: redis
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
      FIREBASE_URL: ${FIREBASE_URL}
      FIREBASE_LEGACY_TOKEN: ${FIREBASE_LEGACY_TOKEN}
    command: docker/start.sh worker
    depends_on:
      - db
      - redis

  worker-ui:
    <<: *base
    profiles:
      - donotstart
    ports:
      - 4000:4000
    command: docker/start.sh worker-ui
    depends_on:
      - worker

  migrate:
    <<: *base
    profiles:
      - donotstart
    environment:
      NODE_ENV: development
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
    depends_on:
      - db
    command: docker/start.sh migrate:latest

  test-unit:
    <<: *base
    profiles:
      - donotstart
    command: docker/start.sh test:unit

  test-integration:
    <<: *base
    profiles:
      - donotstart
    environment:
      REDIS_HOST: redis
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
      FIREBASE_URL: ${FIREBASE_URL}
    command: docker/start.sh test:integration
    depends_on:
      - db
      - redis
