version: "3.9"
networks:
  development:
    external: true
services:
  event-flow-framework:
    container_name: event-flow-framework
    ports:
      - 6000:6000
    volumes:
      - ../:/workspace:cached
    build:  
      context: ../
      dockerfile: ./.devcontainer/dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - development
