version: "3.8"
services:
  alertmanager:
    image: quay.io/kubealex/eda-alertmanager
    ports: "9093:9093"
    hostname: alertmanager
    networks:
      - eda-ansible
    volumes:
      - ./alertmanager/:/etc/alertmanager:Z

networks:
  eda-ansible:
    name: eda-ansible

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
