version: "3.9"

services:
  auth-service:
    depends_on:
      - auth-postgres
    container_name: auth-service
    image: tobiaszimmer/exam_auth_service:feat-0.1.0
    ports:
      - "8888:8080"
      - "50051:50051"
    command:
      - application # Override the command because otherwise it would fail when trying to subscribe to a gateway which is not currently running
    environment:
      POSTGRES_HOST: auth-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      TOKEN_DURATION_HOURS: 12
    networks:
      gateway:
  auth-postgres:
    container_name: auth-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      gateway:

networks:
  gateway:
    external: true