version: '7.2'
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    environment:
      CACHE_DB: fairhub
      CACHE_HOST: localhost
      CACHE_PORT: 6379
      CACHE_URL: redis://127.0.0.1:6379
      CACHE_KEY_PREFIX: $fairhub-io
      CACHE_TIMEOUT: 86400
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
