version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    #build: './myapi'
    image: 'easychen/fangtang-tree:latest'
    command: npm run startwithnode
    environment:
      - IMAGEBASE=http://localhost:3000/image/
      - REGKEY=fangtang111
      - SECRET=2435g233
      - PORT=3000
      - NODE_ENV=product
      - DATABASE_URL=mongodb://mongodb:27017/tree
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./image:/app/image  