version: '3'

services:
  redis:
    image: "redis:alpine"
    network_mode: "host"

  nprobe:
    image: "ntop/nprobe:latest"
    command: ['/usr/bin/nprobe', '--interface', 'eth1', '--zmq', 'tcp://{{ ansible_default_ipv4.address }}:5556']
    cap_add:
      - NET_ADMIN
    network_mode: "host"

  ntopng:
    image: "ntop/ntopng:latest"
    command: ["/usr/bin/ntopng", "-i", "tcp://{{ ansible_default_ipv4.address }}:5556c", "-F", "kafka;{{ ansible_default_ipv4.address }}:{{ kafkaPort }};ntopngFlows"]
    cap_add:
      - NET_ADMIN
    network_mode: "host"   
    depends_on:
     - redis
     - nprobe