version: '3.5'
services:
  <%= appName %>-dev:
    ports:
      - "7071:7071"
    environment: 
      AZURE_FUNCTIONS_ENVIRONMENT: "Development"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:7071"
      WEBSITE_HOSTNAME: "localhost:7071"
    volumes:
      - ./bin/Debug/netcoreapp3.1:/home/site/wwwroot
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: <%= appName %>:dev
    container_name: <%= appName %>
    restart: always
  <%= appName %>-prod:
      ports:
        - "80:80"
      environment: 
        AZURE_FUNCTIONS_ENVIRONMENT: "Production"
        ASPNETCORE_ENVIRONMENT: "Production"
      volumes:
        - ./bin/Release/netcoreapp3.1:/home/site/wwwroot
      build:
        context: .
        dockerfile: Dockerfile.prod
      image: <%= appName %>:latest
      container_name: <%= appName %>
      restart: always
