version: '3.9'

services:
    postgres:
        image: postgres
        container_name: ${PG_CONTAINER_NAME}
        restart: unless-stopped
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - ${PGDATA}:/var/lib/postgresql/data
        ports:
          - ${PGPORT}:5432

volumes:
  postgres_data: