services:
  api:
    build:
      context: ./api
      target: development
    command: /usr/local/bin/hoarder
    working_dir: /usr/src
    ports:
      - '8080:8080'
    environment:
      LOG_LEVEL: debug,hyper=info
      PORT: '8080'
      LOCALE: ja-JP
      PGHOST: database
      PGDATABASE: hoarder
      PGUSER: hoarder
      PGPASSWORD: hoarder
      PGSSLMODE: disable
      MEDIA_ROOT_DIR:
      MEDIA_ROOT_URL:
    volumes:
      - type: bind
        source: .
        target: /usr/src

  static:
    image: nginx:1.26
    ports:
      - '8081:80'
    volumes:
      - type: bind
        source: ./static
        target: /etc/nginx/templates
        read_only: true

  ui:
    build:
      context: ./ui
      target: development
    command: yarn dev
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      BASE_URL: http://localhost:3000
      API_URL: http://api:8080
    volumes:
      - type: bind
        source: ./ui
        target: /usr/src

  database:
    image: postgres:16.2
    environment:
      PGUSER: hoarder
      POSTGRES_DB: hoarder
      POSTGRES_USER: hoarder
      POSTGRES_PASSWORD: hoarder
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data

volumes:
  database:
    driver: local
