version: "3.8"

services:
  hogwartsbackend:
    container_name: hogwartsbackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5433:5432"

  frontend:
    container_name: hogwartsfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - hogwartsbackend 


