version: '3'

services:
  app:
    build: .
    restart: always
    environment: 
      - HOST=httpsproxy2http.novalagung.com
      - EMAIL=caknopal@gmail.com
      - ENV=production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - storage-app:/etc/letsencrypt/live

volumes:
  storage-app:
