version: "3.4"

services:
  release-{{RELEASE_VERSION}}:
    image: {{RELEASE_IMAGE_VERSION}}
    container_name: release-{{RELEASE_VERSION}}
    environment:
      - ACCEPT_EULA=Y
      - ADMIN_PASSWORD=admin
      - GENERATE_XL_CONFIG=false
      - PLUGINS_TO_EXCLUDE={{RELEASE_PLUGINS_TO_EXCLUDE}}
      - PLUGIN_SOURCE=filesystem
    ports:
      - {{RELEASE_SERVER_HTTP_PORT}}:5516
    volumes:
      - ./conf:/opt/xebialabs/xl-release-server/conf
      - ./hotfix/lib:/opt/xebialabs/xl-release-server/hotfix/lib
      - ./hotfix/plugins:/opt/xebialabs/xl-release-server/hotfix/plugins
      - ./plugins:/opt/xebialabs/xl-release-server/plugins
