version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.122.1.142 # replace that with your own local ipv4 addr.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # kafka:
  #   image: confluentinc/cp-kafka:5.5.0
  #   hostname: kafka
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
  app:
    build: .
    ports:
      - 8080:8080
    environment: 
      KAFKA_1: kafka:9092
    depends_on:
      - kafka