version: '3.8'

services:
  boot-node:
    container_name: boot-node
    environment:
       IRONBAR_VERSION: 0.0.2
       IRONBAR_TYPE: boot
       IRONBAR_WRITE_API_KEY: 829ABECB472A49FAAE8436730E3716EE
       IRONBAR_READ_API_KEY: D6C9EF21D256495985269548D5FF70AA
       IRONBAR_READ_DETAILS_API_KEY: CD0A9C4A7B7E4B1DB47F6FAF889A8FF6
       IRONBAR_ADMIN_API_KEY: 789A3BC0A4189477FBCB931FE8BA480BC0
    build:    
      context: .
      dockerfile: boot_node.dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./app:/app
    networks:
      - ironbar-network

  child-node:
    container_name: child-node
    environment:
      IRONBAR_TYPE: child
      IRONBAR_BOOT_SERVER: http://boot-node:50051
      IRONBAR_RPC_PORT: 50040
    build:
      context: .
      dockerfile: boot_node.dockerfile
    ports:
      - "50040:50040"
    volumes:
      - ./app:/app
    networks:
      - ironbar-network

networks:
  ironbar-network:
    driver: bridge