version: '3.2'

services:

  karmabot:
    container_name: karmabot
    restart: always
    image: bomzheg/karmabot
    volumes:
      - type: "bind"
        source: "./config"
        target: "/config"
        read_only: true
    env_file: config/.env
    entrypoint: [ "python3", "-m", "app", "-p" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: nginx-reverse-proxy
