version: "3.9"

services:
  productclient:
    build: client
    image: deni1688/pui:latest
    ports:
      - "8877:80"
    networks:
      - kubestore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  publisherserver:
    build: publisher
    image: deni1688/publisherserver:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      RABBIT_MQ_URI: rabbitmq.yaml
    depends_on:
      - rabbitmq
    networks:
      - kubestore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  catalogserver:
    build: catalog
    image: deni1688/catalogserver:latest
    restart: unless-stopped
    environment:
      RABBIT_MQ_URI: rabbitmq.yaml
    depends_on:
      - rabbitmq
    networks:
      - kubestore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  warehouseserver:
    build: warehouse
    image: deni1688/warehouseserver:latest
    restart: unless-stopped
    environment:
      RABBIT_MQ_URI: rabbitmq.yaml
    depends_on:
      - rabbitmq
    networks:
      - kubestore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kubestore_net

networks:
  kubestore_net:


