version: '3'

services:
  qdrant_database:
    container_name: qdrant
    image: qdrant/qdrant
    build: .
    volumes:
      - "./data/qdrant_data:/qdrant/storage"
    ports:
      - ${QDRANT_PORT}:6333

    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M
    networks:
      - rag_network


  main_stream:
    image: llamaindex-project
    container_name: llamaindex-project
    build: .
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 300M
    environment:
      QDRANT_MODE: docker
      QDRANT_URL: qdrant_database

    ports:
      - ${FASTAPI_PORT}:8000
    networks:
      - rag_network

#
#
networks:
  rag_network:
    driver: bridge
