version: '3.8'

services: 
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./data/.parisneo:/root/.parisneo/
      - ./configs:/srv/configs
    environment:
      - HOME=/data
    tty: true
    stdin_open: true
    ports: 
      - "9600:9600"
