version: '3.7'
services:
  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6378:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
