version: Compose-Spec

services:

  tester:
    image: ytabuchi/net-client:latest
    working_dir: /exam
    volumes:
      - ./script.bash:/exam/script.bash:cached
    tty: true

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: exam
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exam
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
