version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=postgres-playground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
