version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - rs_data:/var/lib/redisstack/data
volumes:
  rs_data:
    driver: local
