version: '3'
services:
#  client:
#    build:
#      context: ./client
#      dockerfile: Dev_Dockerfile
#    container_name: 'nest-todo-dev-client'
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
#    volumes:
#      - ./client/src:/app/client/src
#      - ./client/public:/app/client/public
#    depends_on:
#      - server
#    restart: always
#  server:
#    # 构建目录
#    build:
#      context: ./server
#      dockerfile: Dev_Dockerfile
#    # 容器名
#    container_name: 'nest-todo-dev-server'
#    # 暴露端口
#    expose:
#      - 4200
#    ports:
#      - 4200:4200
#    # 环境变量
#    environment:
#      - DOCKER_ENV=true
#    restart: always
#    volumes:
#      - ./server/src:/app/server/src
#    depends_on:
#      - mariadb
#      - redis
  mariadb:
    image: mariadb
    container_name: 'nest-todo-mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
      MARIADB_DATABASE: 'nest_todo'
    ports:
      - 3306:3306
    restart: always
  redis:
    image: redis
    container_name: 'nest-todo-redis'
    ports:
      - 6379:6379
    restart: always