version: "3.3"

services:
  dashboard:
    image: nz_image_url
    restart: always
    volumes:
      - ./data:/dashboard/data
      - ./static-custom/static:/dashboard/resource/static/custom:ro
      - ./theme-custom/template:/dashboard/resource/template/theme-custom:ro
      - ./dashboard-custom/template:/dashboard/resource/template/dashboard-custom:ro
    ports:
      - nz_site_port:80
      - nz_grpc_port:nz_grpc_port
