interface: 0.0.0.0
port: 3001
secret: "developmentindocker"
use_reverse_proxy: true
debug: false
database:
  url: postgresql://postgres:developer@psql:5432/nf_cloud
  pool_size: 4 # In development mode, more than one connections are supported
rabbit_mq:
  url: "amqp://admin:developer@rabbitmq:5672/%2f"
redis_url: redis://redis:6379/0
worker_credentials:
  username: "worker"
  password: "developer"
login_providers:
  openid:
    dev:
      description: Login with local Fusionauth
      client_id: c63f35e8-66dc-4ec3-bb34-b29803ba72f1
      client_secret: 8CLrA9gAVmlM7GKKCnMnT9MHNvUMqXNVWog2kWUuC7Y2iBOnFIh9X0rpCqfMcpfQkEZfCBfxMqfz5FYC6cduB20kxqV5Ysq
      discovery_url: https://ENV['NF_HOSTNAME']:ENV['NF_FUSIONAUTH_PORT']/.well-known/openid-configuration/04690b25-d20a-158d-5b27-a4202477074b
      scope: "offline_access"
      verify_ssl: false
frontend_host_url: ~
workflows:          # Will be completely overridden by local config
  "Hello World (Locally)":
    directory: ./test_workflows/hello_world
    script: "main.nf"
    args:
      dynamic:
        inFile:
          type: path
          desc: Single file
          selectable_files: true
          selectable_folders: false
        inFolder:
          type: path
          desc: Single folder
          selectable_files: false
          selectable_folders: true
        inFiles:
          type: paths
          desc: Multiple files
          selectable_files: true
          selectable_folders: false
        inFolders:
          type: paths
          desc: Multiple folder
          selectable_files: false
          selectable_folders: true
        txtFiles:
          type: file-glob
          desc: File "regex", e.g. *.txt
        numberOfNewlines:
          type: number
          desc: Number input 
        singleLineText:
          type: text
          desc: Single line text
        multilineText:
          type: text
          desc: Multiline text
          is_multiline: true
      static:
        outDir:
          type: text
          value: ./
  "Hello World (Docker)":
    directory: ./test_workflows/hello_world
    script: "main.nf"
    nextflow_parameters:
      - "-with-docker"
      - "nfcore/base"
    args:
      dynamic:
        inFile:
          type: path
          desc: Single file
          selectable_files: true
          selectable_folders: false
        inFolder:
          type: path
          desc: Single folder
          selectable_files: false
          selectable_folders: true
        inFiles:
          type: paths
          desc: Multiple files
          selectable_files: true
          selectable_folders: false
        inFolders:
          type: paths
          desc: Multiple folder
          selectable_files: false
          selectable_folders: true
        txtFiles:
          type: file-glob
          desc: File "regex", e.g. *.txt
        numberOfNewlines:
          type: number
          desc: Number input 
        singleLineText:
          type: text
          desc: Single line text
        multilineText:
          type: text
          desc: Multiline text
          is_multiline: true
      static:
        outDir:
          type: text
          value: ./
