services:

  bootstrap:
    build:
      context: .
      dockerfile: testnet/Dockerfile
    ports:
      - "3000:3000/udp"
      - "18080:18080/tcp"
    volumes:
      - ./testnet:/etc/nomos
    environment:
      - BOOTSTRAP_NODE_KEY=${DOCKER_COMPOSE_BOOSTRAP_NET_NODE_KEY:-1000000000000000000000000000000000000000000000000000000000000000}
      - LIBP2P_NODE_MASK=${DOCKER_COMPOSE_LIBP2P_NODE_KEY_MASK:-2000000000000000000000000000000000000000000000000000000000000000}
      - LIBP2P_REPLICAS=${DOCKER_COMPOSE_LIBP2P_REPLICAS:-1}
      - OVERLAY_NODES=${DOCKER_COMPOSE_OVERLAY_NODES:-1000000000000000000000000000000000000000000000000000000000000000}
    entrypoint: /etc/nomos/scripts/run_bootstrap_node.sh

  libp2p-node:
    build:
      context: .
      dockerfile: testnet/Dockerfile
    volumes:
      - ./testnet:/etc/nomos
    deploy:
      replicas: ${DOCKER_COMPOSE_LIBP2P_REPLICAS:-1} 
    depends_on:
      - bootstrap
      - etcd
    environment:
      - LIBP2P_REPLICAS=${DOCKER_COMPOSE_LIBP2P_REPLICAS:-1}
      - ETCDCTL_ENDPOINTS=${DOCKER_COMPOSE_ETCDCTL_ENDPOINTS:-etcd:2379}
      - ETCDCTL_API=${DOCKER_COMPOSE_ETCDCTL_API:-3}
      - LIBP2P_NODE_MASK=${DOCKER_COMPOSE_LIBP2P_NODE_KEY_MASK:-2000000000000000000000000000000000000000000000000000000000000000}
      - OVERLAY_NODES=${DOCKER_COMPOSE_OVERLAY_NODES:-1000000000000000000000000000000000000000000000000000000000000000}
      - OVERLAY_SUPER_MAJORITY_THRESHOLD=${DOCKER_COMPOSE_SUPER_MAJORITY_THRESHOLD:-1}
      - NET_INITIAL_PEERS=${DOCKER_COMPOSE_NET_INITIAL_PEERS:-/dns/bootstrap/udp/3000/quic-v1}
    entrypoint: /etc/nomos/scripts/run_nomos_node.sh

  etcd:
    image: quay.io/coreos/etcd:v3.4.15
    ports:
      - "2379:2379/tcp"
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
