services:
  postgresql:
    image: odinsmr/odin_db:latest
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: pg_isready -h localhost -U odinop -d odin || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5m
      start_interval: 20s

  level2db:
    image: mongo
    ports: 
      - 127.0.0.1:27017:27017
    healthcheck:
      test: mongosh --quiet mongodb://localhost --eval "db.stats()"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5m
      start_interval: 10s
    command: mongod --quiet
