version: '2'
services:
  web:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 200000
      port: 8069
      unhealthy_threshold: 50
      initializing_timeout: 60000
      interval: 200000
      strategy: none
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  postgres:
    scale: 1
    start_on_create: true
