
services:
  rstudio-server:
    extends:
      # file: ../compose/R-compose.yaml
      file: ../module/OHDSI/R/R-compose.yaml
      service: rstudio-server
    volumes:
      - ../../webtools/rstudio/home:/home
      - ../../webtools/rstudio/tmp:/tmp

  ohdsi-webapi-pg:
    extends:
      file: ../module/OHDSI/WebAPI/WebAPI-compose.yaml
      service: ohdsi-webapi-pg
  
  ohdsi-webapi:
    extends:
      file: ../module/OHDSI/WebAPI/WebAPI-compose.yaml
      service: ohdsi-webapi
    depends_on:
      - ohdsi-webapi-pg

  ohdsi-atlas:
    extends:
      file: ../module/OHDSI/Atlas/Atlas-compose.yaml
      service: ohdsi-atlas
    volumes:
      - ../module/OHDSI/Atlas/src/config-local.js:/tmp/config-local.js:ro
      - ../module/OHDSI/Atlas/src/envsubst.sh:/tmp/envsubst.sh:ro
    depends_on:
      - ohdsi-webapi-pg
      - ohdsi-webapi

volumes:
  ohdsi-webapi-db:
    name: ohdsi-webapi-db

networks:
  omop-cloudbuild:
    external: true
    name: omop-cloudbuild # Needed for Continuous integration