--- 
version: '2'

services:
  mongo-repair:
    image: mongo:3.4
    restart: always
    volumes:
      - "${WEBITEL_DIR}/mongodb:/data/db"
    command: --repair
    ulimits:
      nproc: 65535
      nofile: 65535
  postgres9:
    image: postgres:9.6-alpine
    container_name: postgres9
    environment:
      - "POSTGRES_DB=webitel"
      - "POSTGRES_USER=webitel"
      - "POSTGRES_PASSWORD=webitel"
    volumes:
      - "${WEBITEL_DIR}/pgsql:/var/lib/postgresql/data"
  postgres10:
    image: postgres:10.3-alpine
    container_name: postgres10
    environment:
      - "POSTGRES_DB=webitel"
      - "POSTGRES_USER=webitel"
      - "POSTGRES_PASSWORD=webitel"
    volumes:
      - "${WEBITEL_DIR}/pgsql:/var/lib/postgresql/data"
  cdr-upgrade:
    image: "webitel/cdr-migration"
    environment:
      - "rabbitmq_host=amqp://webitel:${WEBITEL_PASS}@172.17.0.1?heartbeat=0"
