version: '2'
services: 
  mssqldb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mssqlserver
    restart: always
    hostname: mssqldb
    environment:
      SA_PASSWORD: Password123          #password /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password123'
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"                     # port
    volumes:
      - "./rdmbs/mssql/data:/var/opt/mssql/data" # db
      - "./rdmbs/mssql/backup:/var/opt/mssql/backup"      # backup