services:
  web:
    image: 'ghcr.io/kofuk/premises:latest'
    environment:
      - 'PREMISES_MODE=web'
      - 'premises_debug_web'
      - 'premises_conoha_username'
      - 'premises_conoha_password'
      - 'premises_conoha_tenantId'
      - 'premises_conoha_services_identity'
      - 'premises_conoha_services_compute'
      - 'premises_conoha_services_network'
      - 'premises_conoha_services_volume'
      - 'premises_conoha_nameTag'
      - 'premises_s3_endpoint'
      - 'premises_s3_bucket'
      - 'premises_aws_accessKey'
      - 'premises_aws_secretKey'
      - 'premises_game_operators'
      - 'premises_game_whitelist'
      - 'premises_controlPanel_secret'
      - 'premises_controlPanel_origin'
      - 'premises_controlPanel_redis_address=redis:6379'
      - 'premises_controlPanel_redis_password='
      - 'premises_controlPanel_postgres_address=postgres'
      - 'premises_controlPanel_postgres_port=5432'
      - 'premises_controlPanel_postgres_user=premises'
      - 'premises_controlPanel_postgres_password=password'
      - 'premises_controlPanel_postgres_dbName=premises'
      - 'premises_controlPanel_proxyApi=http://proxy:8001'
      - 'premises_controlPanel_gameDomain'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - '8000:8000'
    command: [web]
  proxy:
    image: 'ghcr.io/kofuk/premises:latest'
    environment:
      - 'PREMISES_MODE=proxy'
      - 'premises_controlPanel_postgres_port=5432' # TODO: We should remove this after #406 fixed.
      - 'premises_controlPanel_iconUrl'
    ports:
      - '25565:25565'
    command: [proxy]
  redis:
    image: 'redis:7-alpine'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 30s
      retries: 30
    restart: always
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=premises
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=premises
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-Upremises"]
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
