version: "3"

x-aws-logs_retention: 14

networks:
  datagrok:

services:

  datagrok:
    image: datagrok/datagrok:latest
    x-aws-policies:
      - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    environment:
      GROK_MODE: 'auto'
      GROK_PARAMETERS: "{
        \"amazonStorageRegion\": \"${DATAGROK_S3_BUCKET_REGION}\",
        \"amazonStorageBucket\": \"${DATAGROK_S3_BUCKET_NAME}\",
        \"dbServer\": \"${DATAGROK_RDS_ENDPOINT}\",
        \"db\": \"datagrok\",
        \"dbLogin\": \"datagrok\",
        \"dbPassword\": \"SoMeVeRyCoMpLeXpAsSwOrD\",
        \"dbAdminLogin\": \"postgres\",
        \"dbAdminPassword\": \"postgres\",
        \"dbSsl\": false,
        \"deployDemo\": false,
        \"deployTestDemo\": false
      }"
    ports:
      - 80:80
      - target: 8080
        x-aws-protocol: http
        protocol: tcp
    networks:
      - datagrok
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 2G

#  grok_connect:
#    image: datagrok/grok_connect:latest
#    networks:
#      - datagrok
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 400M
#        reservations:
#          cpus: '0.25'
#          memory: 200M

x-aws-cloudformation:
  Resources:
    DatagrokTCP8080Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: DatagrokTCP8080TargetGroup
            Type: forward
        Protocol: "HTTP"
    DatagrokTCP8080TargetGroup:
      Properties:
        HealthCheckPath: /api/admin/health
        HealthCheckIntervalSeconds: 60
        UnhealthyThresholdCount: 5
        Matcher:
          HttpCode: 200
    DatagrokTCP80Listener:
      Properties:
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: DatagrokTCP8080TargetGroup
            Type: forward
        Protocol: "HTTP"
    DatagrokTCP80TargetGroup:
    DatagrokService:
      Properties:
        LoadBalancers:
          - ContainerName: datagrok
            ContainerPort: 8080
            TargetGroupArn:
              Ref: DatagrokTCP8080TargetGroup
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
