---
# this docker-compose is for developing the quotes application
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports: [5000:5000]
    volumes: [./frontend:/app]
    restart: always
    entrypoint: [flask, run, -h, 0.0.0.0] # overwrite entrypoint with development flask webserver
    environment:
      FLASK_ENV: development
      ENABLE_KUBERNETES_FEATURES: "false" # disable k8s specific functionality
      BACKEND_HOST: backend
      BACKEND_PORT: 5000

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports: [8888:5000]
    volumes: [./backend:/app]
    restart: always
    entrypoint: [flask, run, -h, 0.0.0.0] # overwrite entrypoint with development flask webserver
    environment:
      FLASK_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: superuser
      DB_PASSWORD: complicated
      DB_NAME: quotes

  postgres:
    container_name: postgres
    image: postgres:14.3
    ports: [5432:5432]
    volumes: [postgres:/var/lib/postgresql/data]
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: complicated
      POSTGRES_DB: quotes

  # handy GUI for checking that things changed in the db
  adminer:
    image: adminer
    restart: always
    ports: [8080:8080]

volumes:
  postgres:
