# Example Pod Template
# comments are allowed, thanks yaml ;)
# This defines a pod of two apps: etcd and debian
# The debian app is only for illustrative purpuses, but can be a good idea
# to include if you want to debug your pod at runtime.
---
name: etcd-example
# you can specify cpu and memory isolators!
cpu: 250m
memory: 32M
# networks to join can be specified here
networks:
  - my-net
manifest: # This maps one to one to the pod-manifest.
  apps:
    - name: etcd
      image:
        # No ID needs to be specified here.
        name: quay.io/coreos/etcd
        labels:
          - name: version
            value: v3.2.0
      app:
        exec: [ /usr/local/bin/etcd, --log-output, stdout ]
        # user and group are defaulting to "0"
    - name: debian
      image:
        name: docker://debian:testing # docker url support!
      app:
        exec: [ tail, -f, /dev/null ]
