version: "3"
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9091:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${PW}
    volumes:
      - /home/syran/sandbox/docker/minio:/data
    command: server /data --console-address ":9090"
