# Docker Compose file that brings up containers necessary for NIBRS analytics
# To run:  docker-compose -f nibrs-analytics-compose.yaml up -d

version: '3.2'

networks:
  nibrs_analytics_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      -
       subnet: 172.15.0.0/16

services:
   nibrs-analytics-db:
    container_name: nibrs-analytics-db
    image: searchncjis/nibrs-analytics-db
    networks:
      nibrs_analytics_nw:
# uncomment to open port for loading from host
#    ports:
#      - "23306:3306"
   nibrs-analytics-saiku:
    container_name: nibrs-analytics-saiku
    image: searchncjis/nibrs-analytics-saiku
    # use the dev tagged verison if you want access to the admin console in Saiku
    #image: searchncjis/nibrs-analytics-saiku:dev
    networks:
      nibrs_analytics_nw:
    ports:
      - "8080:80"
    depends_on:
      - nibrs-analytics-db
