version: "2.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1027
      - PGID=100
      - VERSION=${PLEX_VERSION:-docker}
      - 'PLEX_CLAIM=${PLEX_CLAIM}'
    ports:
      - "32400:32400"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/docker/downloads:/volume1/docker/downloads
#      - /volume1/docker/transmission-openvpn/completed:/volume1/docker/transmission-openvpn/completed
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.rule=Host(`${PLEX_DOMAIN:-}`)
    restart: unless-stopped