version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data
      - ${PWD}/00-init-sensorcentral-db.sh:/docker-entrypoint-initdb.d/00-init-sensorcentral-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=password
  
