version: "3.7"
name: shortcut
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    container_name: django
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "cd backend && uvicorn backend.asgi:app --host 0.0.0.0 --port 8000"
    # command: bash -c "uwsgi --ini uwsgi.ini  --uid 5432"
  mysql:
    image: mysql:5.7
    container_name: mysqldjango
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 33061:3306
    volumes:
      - ./mysql:/var/lib/mysql