version: "3"

services:
  etl-app:
    build: ..
    image: topcoder-skills-etl:latest
    command:
      - "/app/index.js"
    environment:
      INFORMIX_HOST: informix
      DYNAMODB_ENDPOINT: http://dynamo:8000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  list-results:
    build: ..
    image: topcoder-skills-etl:latest
    command:
      - "/app/scripts/list-aggregated-skills.js"
    environment:
      DYNAMODB_ENDPOINT: http://dynamo:8000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

networks:
  default:
    external:
      name: skills-etl