stunnel:
  image: easypi/stunnel-arm
  ports:
    - "1194:1194"
  environment:
    - CLIENT=yes
    - SERVICE=openvpn
    - ACCEPT=0.0.0.0:1194
    - CONNECT=server:4911
  extra_hosts:
    - server:1.2.3.4
  restart: always

openvpn:
  image: easypi/openvpn-arm
  command: --config pi.ovpn
  volumes:
    - ./data:/etc/openvpn
  net: host
  privileged: yes
  restart: always

dnsmasq:
  image: easypi/dnsmasq-arm
  volumes:
    - ./data/dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf
  cap_add:
    - NET_ADMIN
  net: host
  restart: always
