services:
  hz-pipeline:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/sample-pipeline/target/spring-hazelcast-pipeline-dispatcher-sample-pipeline-1.1.1.jar
        hazelcast.platform.solutions.pipeline.dispatcher.sample.ExamplePipeline
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - clientserver

  clientserver-app:
    image: amazoncorretto:11
    command: >
      java
        -Dhazelcast.pipeline.dispatcher.embed_hazelcast=false 
        -Dhazelcast.pipeline.dispatcher.request_timeout_ms=1000  
        -Dhazelcast.client.config=/opt/project/sample-application/config/hazelcast-client.yaml
        -Dlogging.level.hazelcast.platform.solutions=WARN
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.1.1.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - clientserver

  embedded-app:
    image: amazoncorretto:11
    command: >
      java 
        -Dhazelcast.pipeline.dispatcher.embed_hazelcast=true 
        -Dhazelcast.pipeline.dispatcher.request_timeout_ms=1000
        -Dhazelcast.config=/opt/project/sample-application/config/hazelcast.yaml
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.1.1.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - embedded

  mc:
    image: hazelcast/management-center:5.2.1
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz-pipeline:5701
    ports:
      - "8888:8080"
    networks:
      - default
    profiles:
      - clientserver

  embedded-mc:
    image: hazelcast/management-center:5.2.1
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: embedded-app:5701
    ports:
      - "8888:8080"
    networks:
      - default
    profiles:
      - embedded

  load-routing-config:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/solution/target/spring-hazelcast-pipeline-dispatcher-1.1.1.jar:/opt/project/solution/target/dependency/*
           hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool load 
           --hz-cluster-name dev --hz-servers hz-pipeline:5701 --input /opt/project/reverse_routing.json
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - disabled

  dump-routing-config:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/solution/target/spring-hazelcast-pipeline-dispatcher-1.1.1.jar:/opt/project/solution/target/dependency/*
           hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool dump 
           --hz-cluster-name dev --hz-servers hz-pipeline:5701
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - disabled

  embedded-load-routing-config:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/solution/target/spring-hazelcast-pipeline-dispatcher-1.1.1.jar:/opt/project/solution/target/dependency/*
           hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool load 
           --hz-cluster-name dev --hz-servers embedded-app:5701 --input /opt/project/reverse_routing.json
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - disabled

  embedded-dump-routing-config:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/solution/target/spring-hazelcast-pipeline-dispatcher-1.1.1.jar:/opt/project/solution/target/dependency/*
           hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool dump 
           --hz-cluster-name dev --hz-servers embedded-app:5701
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - disabled

networks:
  default: {}