type: object
additionalProperties:
  type: object
  properties:
    build:
      type: object
      properties:
        context:
          type: string
          example: ./dir
        dockerfile:
          type: string
          example: Dockerfile-alternate
        args:
          type: object
          additionalProperties:
            type: string
    image:
      type: object
      properties:
        name:
          type: string
          example: eoscsynergy/sqaaas-api-spec:1.0.0
        registry:
          type: object
          properties:
            push:
              type: boolean
            credential_id:
              type: string
              example: my-dockerhub-cred
      required:
        - name
    hostname:
      type: string
      example: sqaaas-host
    volumes:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum: [bind]
          source:
            type: string
            example: ./
          target:
            type: string
            example: ./sqaaas-build
    command:
      type: string
      example: sleep 600000
    environment:
      $ref: './Environment.yaml'
    oneshot:
      type: boolean
      default: true
