version: "3.8"
services:
  Stage-Oracle:
    image: 'wexio/so-front'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    #environment:
    #  - VITE_REGISTRATION_API_URL=http://127.0.0.1:51929
    #  - VITE_PRODUCTION_API_URL=http://127.0.0.1:51943