version: "3"
services:
  app:
    image: agcs-claims-incurred-anomaly:latest
    hostname: anomaly
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: agcs-claims-incurred-anomaly