spring:
  config.activate.on-profile: compose

  applikasjon:
    datasource:
      hikari:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: test
        driver-class-name: org.postgresql.Driver
  datavarehus:
    flyway:
      locations: /db/test-datavarehus
    datasource:
      hikari:
        url: "jdbc:postgresql://localhost:5433/postgres"
        username: postgres
        password: test
        driver-class-name: org.postgresql.Driver

altinn:
  url: "http://localhost:8585/altinn/"
  apikey: "test"
  apigw.apikey: "test"
  proxy:
    url: "http://localhost:8585/proxy/"
  iaweb.service:
    code: 3403
    edition: 2

enhetsregisteret:
  url: "http://localhost:8585/enhetsregisteret"

nais.cluster.name: local

kafka:
  outbound:
    bootstrapServers: localhost:9092
    securityProtocol: PLAINTEXT

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: http://localhost:6969/tokenx/.well-known/openid-configuration
      accepted_audience: aud-localhost

tokenxclient:
  clientId: localhost:arbeidsgiver:ia-tjenester-metrikker
  token_endpoint: http://localhost:6969/tokenx/.well-known/openid-configuration/token
  altinn_rettigheter_proxy_audience: localhost:arbeidsgiver:altinn-rettigheter-proxy
  jwk: '{
      "kty": "RSA",
      "d": "BRcX3ywynvH9WA5wOz_vU9HzSY6OkmRKOGGqLEG_fEtVcXwxReSSuVcXZUngZrPkoC3li-jvNfDz9c_7WP44HkO07RkG10mSspLjS-EarYg5HUI8JPfrjtacCVmq0pnVlvEeR-35x1e91o6iC5-hEGQPkBgImKwuFy1u2eiPBM-mIoNHOSpO5IqHBAP2Gi2w7SU28mZ1xt2xmvj6kGE96u3G6nSkr175tgdi0tHO9T7BCYFjr1NNkLojzExpo5gUVyNsm17ahMi2XE7NIRdduHkEXcprr5DayDK7_VaQYqa3OPsN3UcRZanXcpdFt9HHt8KyuRW3zvXJ6-AtM1UCkQ",
      "e": "AQAB",
      "use": "sig",
      "kid": "1",
      "n": "ssXDjDMHXWxvnAFXwJiKqgyf6tn_zHGbkSiWNgHZ2xsQgxo-gzv5JssbJxLCDZCdC5zX7nXIHOC5fid_fxMXGNAYh6xaJzxSLGGAJHSp_uCh5zSPAGFigihxLNwwWaDxYDcLFC9QHzaV__BaB_JUaHyD7aFDUEyQiB4MXAqTkCEUmPj-RTiUbcnicD5Q32zByJ8gzG3ufxuCGnP-xcc5QJQ8TmrlLgNzgiHHdkpRjeXCHovP_gYGXujJkhQ0dvgYtVpgoHeGcH1FC9ZRd6IiFtanJ1MPwg2i6sR_HlE2l3Ua_Knj4FZY3F0cM3P4AgXI8TyEhQgM2GWwPGf6YNrHyQ"
  }'
