services:
  app:
    image: docker.io/procsiab/sylius:v1.2-amd64
    volumes:
      - ./app:/var/www/html/app:Z
    ports:
      - '8080:8000'
  db:
    image: docker.io/amd64/mariadb:10.7.3-focal
    volumes:
      - ./data:/var/lib/mysql:Z
    environment:
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=sylius
      - MYSQL_DATABASE=sylius
      - MYSQL_ROOT_PASSWORD=moresecure
    ports:
      - '13306:3306'
