services:

  ros1_master:
    image: "ghcr.io/ipab-rad/av_radar:1.0.0"
    container_name: ros1_master
    network_mode: "host"
    privileged: true
    command: rosmaster --core

  av_radar:
    image: "ghcr.io/ipab-rad/av_radar:1.0.0"
    container_name: av_radar
    network_mode: "host"
    privileged: true
    depends_on:
      - ros1_master

  ros1_bridge:
    image: "ghcr.io/ipab-rad/ros1_bridge:1.0.0"
    container_name: ros1_bridge
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
    depends_on:
      - av_radar

  av_radar_bridge:
    image: "ghcr.io/ipab-rad/av_radar_bridge:1.0.0"
    container_name: av_radar_bridge
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
    depends_on:
      - ros1_bridge
