services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
    volumes:
      - "./frontend:/app"
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8080:8090
