version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    network_mode: "host"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    links:
      - influxdb

  grafana_import:
    image: curlimages/curl:latest
    command: bash -c /mnt/grafana-import.sh
    volumes:
      - .:/mnt
    links:
      - grafana
    depends_on:
      - grafana
