version: "3.1"
services:
  users-service:
    image: rubencg177/users-service:latest
    container_name: users
    ports:
      - 8091:8091
    networks:
      - mysql_default
networks:
  mysql_default:
    external: true