version: "3.1"

services:
  db:
    container_name: tpm-graphs-db
    depends_on:
      - shell
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    volumes:
      - "./docker/db.init:/docker-entrypoint-initdb.d/"

  shell:
    container_name: tpm-graphs-sh
    image: alpine:3.19
    entrypoint: [ '/bin/sh', '-c' ]
    volumes:
     - "./:/tpm-graphs"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - TPM_DB_URL=postgresql://root@db/tpm
    command:
    - |
      # Install packages
      apk update
      apk add bash patch postgresql14-client
      apk add texlive-full
      apk add py3-matplotlib py3-pip py3-psycopg2 py3-sqlalchemy py3-yaml python3 python3-gdbm
      cd /tpm-graphs
      # texlive-20230506.66984-r2 in alpine is broken -- luatex is compiled
      # against a wrong version of zlib, causing it to abort when searching for
      # files such as fonts. This patch allows matplotlib to use kpsewhich
      # directly should luatex search fail.
      patch /usr/lib/python3.11/site-packages/matplotlib/dviread.py <docker/dviread.py.patch
      # Populate database
      ./tpm-graphs-db >/dev/null 2>&1
      # Create additional functions and views that are complicated with
      # sqlalchemy
      psql -d $${TPM_DB_URL} -1 -Atq -f sql/version.sql
      psql -d $${TPM_DB_URL} -1 -Atq -f sql/view-setup.sql
      # Load the datasets
      for dir in data /data; do
          test -d "$${dir}" && find "$${dir}" -name '*.zip' | ./tpm-graphs-db db.read -
      done
      # Generate graphs
      ./tpm-scan-graphs
      echo "Done"
