version: "3.3"

services:
  tribler-core:
    image: triblercore/triblercore:latest
    container_name: triblercore
    build: .
    volumes:
      - "~/.Tribler:/state"
      - "~/Downloads/TriblerDownloads:/downloads"
    ports:
      - "20100:20100"
    environment:
      - CORE_API_PORT=20100
      - CORE_API_KEY=TEST
      - TORRENT_PORT=7000
      - TSTATEDIR=/state
      - HTTP_HOST=0.0.0.0
