version: "3.9"
services:
  ublox_read_2:

    # Build image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Specify ROS2 distro to use
        - ROS_DISTRO=humble

    # Enable interactive shell in container
    stdin_open: true
    tty: true

    # Mount volumes
    volumes:
      # Mount ublox_read_2 src files
      - .:/ublox_read_2
      # Mount dev folder for USB devices. Can be modified to only specific devices.
      - /dev:/dev

    # Give container sudo access to your host system, needed for USB devices
    privileged: true

    # Give container access to host network. Can be modified to include only specific
    #  ports and addresses, but doing so isn't straightforward for ROS.
    network_mode: host

