version: '3.5'

services: 
  standalone: 
    container_name: vearch-standalone
    image: vearch/vearch:latest
    ports: 
      - "8817:8817"
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config.toml:/vearch/config.toml
    command: all
