version: "3"
services:
  kafka:
    image: spotify/kafka
    hostname: kafka
    ports:
      - "2181:2181"
      - "9092:9092"

  vflow:
    image: mehrdadrad/vflow
    hostname: vflow
    entrypoint: /bin/sh -c "sleep 5 && vflow"
    depends_on:
      - kafka
    environment:
      - VFLOW_KAFKA_BROKERS=kafka:9092
    ports:
      - "4739:4739/udp"
      - "4729:4729/udp"
      - "6343:6343/udp"
      - "9996:9996/udp"
      - "8081:8081"
  prometheus:
    image: prom/prometheus:latest
    hostname: prom
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./scripts:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
