# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     depends_on:
#       - rabbitmq
#   rabbitmq:
#     image: "rabbitmq:3-management"
#     ports:
#       - "5672:5672"
#       - "15672:15672"
