version: '3'
services:
  couchdb:
    image: couchdb:${COUCHDB_IMAGE_TAG:-3.3.2}
    ports:
      - '5984:5984'
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
volumes:
  couchdb:
