version: "3.7"
services:
  mdconn2:
    image: myonara/mdconn:v0.0.17
    environment: 
      NODE_ENV: 'production'
    volumes:
      - "/UNItopia/mudadm/python/rpc/orbit/json:/run/sockets/fifo"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: mudnet
        com.docker.lb.port: 2019
        com.docker.lb.ssl_passthrough: "true"
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 1
        window: 3600s
    ports:
      - "2019:5000"
    networks:
      - mudnet
networks:
  mudnet:
    driver: overlay
