version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  webrtc-streamer:
    image: mpromonet/webrtc-streamer:latest
    command: ["-C", "config.json"]
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources     
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards       
