services:
  web:
    build:
      dockerfile: Dockerfile.web
    image: wiseflow/web
    ports:
      - 8090:8090
    # env_file:
    # - .env
    volumes:
      - ./pb/pb_data:/pb/pb_data
    # - ./${PROJECT_DIR}:/pb/${PROJECT_DIR}
    entrypoint: /pb/pocketbase serve --http=0.0.0.0:8090

  api:
    build:
      dockerfile: Dockerfile.api
    image: wiseflow/api
    tty: true
    stdin_open: true
    entrypoint: bash docker_entrypoint.sh
    env_file:
      - .env
    ports:
      - 7777:7777
    volumes:
      - ./${PROJECT_DIR}:/app/${PROJECT_DIR}
      - ${EMBEDDING_MODEL_PATH}:${EMBEDDING_MODEL_PATH}
      - ${RERANKER_MODEL_PATH}:${RERANKER_MODEL_PATH}
    depends_on:
      - web