version: '3'

networks:
  workspace:
    external: true

services:
  api:
    image: ${CI_REGISTRY_IMAGE}/api:${VERSION}
    container_name: api
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - workspace
    env_file:
      - ./../../.env
    logging: 
      driver: loki
      options:
        loki-url: "${GRAFANA_LOKI_URL}/loki/api/v1/push"
        loki-retries: "1"
        max-file: "1"
        max-size: "500m"

