version: '3.1'
services:
  wukongim:
    image: wukongim/wukongim:latest
    restart: always
    volumes:
      - ~/wukongim:/root/wukongim
    ports:
      - 5001:5001 # http api 端口
      - 5100:5100 # tcp端口
      - 5200:5200 # websocket端口
      - 5300:5300 # monitor端口
      - 5172:5172 # monitor端口

  