version: "3.8"
services:
  webapp:
    image: webapp:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment: ['POSTGRES_PASSWORD=root']
volumes:
  type: bind
  db-data: {}
networks:
  default:
    driver: bridge

